title: 'mj063.github.io'
description: "Site for mj063"
baseurl: ""
url: "http://mj063.github.io"

navigation:
  -name: Main
    url: /
  - name: About
    url: /about
  - name: Archive
    url: /archive

style: dark

footer: 'on <a href="http://github.com/">github</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

footer-text: © 2019 Minju Jang
